from __future__ import annotations

import json
import os
import platform
import re
from pathlib import Path
from typing import Any, Literal, cast

import typer
import yaml
from bashrun import bash, bash_output
from .detect_gpu import GPU_TYPES, Gpu, detect_gpu
from pydantic_settings import BaseSettings

from .context_sha import compute_service_shas


class Settings(BaseSettings):
    wsl_distro_name: str | None = None


settings = Settings.model_validate({})

LOCK_FILE = Path(".env.lock")
ENV_SHAS_FILE = Path(".env.shas")
COMPOSE_FILE = Path("compose.yml")
DEFAULT_BAKE_FILE = Path("compose.bake.yml")
METADATA_PATH = Path("metadata.json")

Mode = Literal["local", "ci"]


app = typer.Typer(add_completion=False, pretty_exceptions_show_locals=False)


def _load_lock_file(path: Path):
    return {
        (p := line.split("=", 1))[0].strip(): p[1].strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if "=" in line and not line.startswith("#")
    }


def _write_lock_file(path: Path, variables: dict[str, str]):
    path.write_text(
        "# Generated by lock.py\n" + "\n".join(f"{k}={v}" for k, v in sorted(variables.items())) + "\n",
        encoding="utf-8",
    )


def _get_remote_digest(image_ref: str):
    print(f"Resolving digest for: {image_ref}...")

    if "$" in image_ref:
        return ""

    try:
        output = bash_output(f"docker buildx imagetools inspect {image_ref}")
        match = re.search(r"^Digest:\s+(sha256:[a-f0-9]+)", output, re.MULTILINE)
        if match:
            return match.group(1)
    except Exception:
        raise RuntimeError(f"Digest resolution failed for: {image_ref}")
    return None


# Vibe code - Gemini 3
def _check_gc_limits(min_gb: int = 60):
    candidates = [Path("/etc/docker/daemon.json"), Path(os.path.expanduser("~/.docker/daemon.json"))]
    if settings.wsl_distro_name is not None:
        try:
            win_home = bash_output('wslpath $(cmd.exe /c "echo %UserProfile%" 2>/dev/null)').strip()
            candidates.append(Path(win_home) / ".docker" / "daemon.json")
        except Exception:
            pass

    config = next((p for p in candidates if p.exists() and os.access(p, os.R_OK)), None)
    if not config:
        print(f"    [WARN] No readable daemon.json found. Ensure defaultKeepStorage > {min_gb}GB.")
        return

    data = json.loads(config.read_text())
    raw = data.get("builder", {}).get("gc", {}).get("defaultKeepStorage")
    if not raw:
        sample = json.dumps({"builder": {"gc": {"defaultKeepStorage": f"{min_gb}GB"}}}, indent=2)
        raise RuntimeError(
            f"Missing 'builder.gc.defaultKeepStorage' in {config}; Docker's default is too low for GPU builds "
            f"(need >= {min_gb}GB). Add the following (merging into any existing keys) and restart Docker:\n\n{sample}"
        )

    m = re.match(r"^(\d+(?:\.\d+)?)\s*([TGMK]i?B)?$", str(raw), re.IGNORECASE)
    if not m:
        raise RuntimeError(f"Could not parse 'defaultKeepStorage' value: {raw}")

    mult = {"T": 1024, "G": 1, "M": 1 / 1024, "K": 1 / 1024**2, "B": 1 / 1024**3}
    unit = (m.group(2) or "B")[0].upper()
    val = float(m.group(1)) * mult.get(unit, 1 / 1024**3)

    if val < min_gb:
        raise RuntimeError(
            f"UNSAFE GC LIMIT: {val:.1f}GB in {config} (Required: {min_gb}GB). RESTART DOCKER AFTER FIXING."
        )

    print(f"    [OK] Docker GC Limit verified: {val:.1f}GB")


def _load_compose(path: Path) -> dict[str, Any]:
    data: dict[str, Any] = yaml.safe_load(path.read_text(encoding="utf-8"))
    for include in data.pop("include", []):
        include_path = path.parent / (include if isinstance(include, str) else include["path"])
        included: dict[str, Any] = yaml.safe_load(include_path.read_text(encoding="utf-8"))
        data.setdefault("services", {}).update(included.get("services", {}))
    return data


@app.command()
def build(
    upgrade: bool = typer.Option(False, "--upgrade", "-u", help="Re-resolve and rewrite base digests."),
    lock_only: bool = typer.Option(False, "--lock-only", help="Update lock file without building images."),
    mode: Mode = typer.Option("local", "--mode", help="local: --load images; ci: --push images + registry caches."),
    gpu: Gpu = typer.Option("auto", "--gpu", help="auto|cuda|rocm|none"),
    no_cache: bool = typer.Option(False, "--no-cache", help="Force rebuild by disabling cache usage."),
    targets_opt: list[str] | None = typer.Option(
        None, "--targets", "-t", help="Build only these services (from the selected bake file)."
    ),
    bake_file: Path = typer.Option(
        DEFAULT_BAKE_FILE, "--bake-file", help="Bake file to load (e.g. compose.bake.yml or compose.zed.bake.yml)."
    ),
) -> None:
    run_build(
        upgrade=upgrade,
        lock_only=lock_only,
        mode=mode,
        gpu=gpu,
        no_cache=no_cache,
        targets_opt=targets_opt,
        bake_file=bake_file,
    )


def run_build(
    *,
    upgrade: bool = False,
    lock_only: bool = False,
    mode: Mode = "local",
    gpu: Gpu = "auto",
    no_cache: bool = False,
    targets_opt: list[str] | None = None,
    bake_file: Path = DEFAULT_BAKE_FILE,
) -> None:
    service_shas = compute_service_shas(Path.cwd(), bake_file)
    os.environ.update(service_shas)

    # Tags of the images built this run — the local analog of .env.lock's pulled
    # digests — so raw `docker compose` can resolve the compose graph's ${*_SHA} holes.
    ENV_SHAS_FILE.write_text(
        "".join(f"{key}={value}\n" for key, value in sorted(service_shas.items())), encoding="utf-8"
    )

    # Read bake, compose, and lock files
    bake_data: dict[str, Any] = yaml.safe_load(bake_file.read_text(encoding="utf-8"))
    compose_data: dict[str, Any] = _load_compose(COMPOSE_FILE)
    lock_data = _load_lock_file(LOCK_FILE) if LOCK_FILE.exists() else {}

    # TOOD: Create separate commands for ci and local modes so typer can do this validation instead of us
    if mode == "ci" and gpu == "auto":
        raise typer.BadParameter("In CI mode, --gpu cannot be 'auto'; specify 'cuda' or 'rocm'.")

    # For local builds, ensure Docker GC limits are high enough that GPU builds don't cause cache evictions
    if mode == "local" and not lock_only and not targets_opt:
        _check_gc_limits(min_gb=60)

    # Resolve gpu
    if gpu == "auto" and not lock_only:
        gpu = detect_gpu()

    # Resolve base image external dependencies
    base_images: dict[str, str] = bake_data["x-base-images"]
    for image, ref in {image: ref for image, ref in base_images.items() if upgrade or image not in lock_data}.items():
        lock_data[image] = f"@{_get_remote_digest(ref)}"

    # Resolve third-party image external dependencies. x-image-ref marks services whose image
    # is sourced externally (vs. built from a bake file), so it's the right discriminator
    # regardless of how many bake files exist.
    third_party_images: dict[str, str] = {
        name.upper().replace("-", "_") + "_IMAGE": config["x-image-ref"]
        for name, config in cast(dict[str, Any], compose_data["services"]).items()
        if "x-image-ref" in config
    }

    def _needs_resolve(image: str, ref: str) -> bool:
        if upgrade or image not in lock_data:
            return True
        # Re-resolve if the image name in compose.yml changed from what's in the lock file
        # (e.g. postgres:16-alpine → postgis/postgis:16-3.4-alpine)
        return not lock_data[image].startswith(ref + "@")

    for image, ref in {image: ref for image, ref in third_party_images.items() if _needs_resolve(image, ref)}.items():
        lock_data[image] = f"{ref}@{_get_remote_digest(ref)}"

    # Update main lock file
    _write_lock_file(LOCK_FILE, lock_data)

    if lock_only:
        return

    # Update environment with external dependency image digests
    os.environ.update(lock_data)

    # Build command arguments
    command_arguments: list[str] = []

    # Determine bake targets
    targets = [
        service
        for service, config in bake_data["services"].items()
        if config.get("build", {}).get("tags")
        and (not any(service.endswith(f"-{g}") for g in GPU_TYPES) or service.endswith(f"-{gpu}"))
    ]

    # Filter to specific targets if requested
    # x-cross-compile-targets: services declared here are excluded from the default
    # target list because they need special (usually per-arch) treatment; an operator
    # can still opt them in explicitly via --targets. The field is a top-level bake key.
    cross_compile_targets: set[str] = set(bake_data.get("x-cross-compile-targets", []))

    if targets_opt:
        unknown = set(targets_opt) - set(bake_data["services"])
        if unknown:
            raise typer.BadParameter(f"Unknown targets: {unknown}. Available: {sorted(bake_data['services'])}")
        targets = [t for t in bake_data["services"] if t in set(targets_opt)]
    else:
        targets = [
            service
            for service in bake_data["services"]
            if (not any(service.endswith(f"-{g}") for g in GPU_TYPES) or service.endswith(f"-{gpu}"))
            and service not in cross_compile_targets
        ]

    # Configure registry caches in CI mode
    if mode == "ci":
        for target in targets:
            target_cache = f"{bake_data['x-registry-cache']}:{target}"
            command_arguments.append(
                f"--set {target}.cache-to+=type=registry,ref={target_cache},mode=max,image-manifest=true,oci-mediatypes=true"
            )
            command_arguments.append(f"--set {target}.cache-from+=type=registry,ref={target_cache}")

    # `docker buildx --load` only writes a single arch to the host image store,
    # so bake targets declared multi-platform get overridden to host arch in
    # local builds. CI uses `--push` and produces the full manifest list.
    # Override key is `platform` (singular) even though the bake field is plural.
    if mode == "local":
        machine = platform.machine().lower()
        if machine in ("x86_64", "amd64"):
            host_platform = "linux/amd64"
        elif machine in ("aarch64", "arm64"):
            host_platform = "linux/arm64"
        else:
            raise RuntimeError(f"Unsupported host architecture: {machine}")
        for target in targets:
            target_platforms = bake_data["services"][target].get("build", {}).get("platforms", [])
            if len(target_platforms) > 1:
                command_arguments.append(f"--set {target}.platform={host_platform}")

    # Load or push images based on mode
    command_arguments.append("--load" if mode == "local" else "--push")

    # Handle no-cache option
    if no_cache:
        command_arguments.append("--no-cache")

    # Append targets
    command_arguments.extend(targets)

    # Clean up any existing metadata file
    METADATA_PATH.unlink(missing_ok=True)

    # Bake images
    command = [
        "docker buildx bake",
        f"-f {bake_file}",
        f"--metadata-file {METADATA_PATH}",
        "--progress auto",
        "--provenance=false",
        "--sbom=false",
    ] + command_arguments
    bash(" ".join(command))

    # Sanity check
    baked_images: dict[str, Any] = json.loads(METADATA_PATH.read_text()) if METADATA_PATH.exists() else {}
    if not set(targets) <= baked_images.keys():
        raise RuntimeError("Baked images do not match target images; something went wrong during the bake.")


def main() -> None:
    app()


if __name__ == "__main__":
    main()
